### ISSUE TITLE
In Backdrop 1.28.0 this module causes the Home text/icon and back to site text/icon to disappear

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/simplei#2]
**Steps to reproduce**

1. Update to 1.28.0
2. Login to account with admin bar access

**Expected result**
![image](https://github.com/backdrop-contrib/simplei/assets/20357797/0fdfa782-d035-4924-9a0c-d876c7a1036e) 
![image](https://github.com/backdrop-contrib/simplei/assets/20357797/3ed11feb-5324-49e6-a292-d3dab5230e22)

**Actual result**
![image](https://github.com/backdrop-contrib/simplei/assets/20357797/6ce458c1-d0f3-420b-ba22-3c947660d530)

**Comment by yorkshire-pudding** [comment]
@herbdool - I've added a PR for this.

**Comment by izmeez** [comment]
I can confirm the problem occurs as described with backdrop 1.28.0 and the changes in the PR fix the problem. Applying the diff as a patch against version 1.x-1.0.3 failed on my local but applying the changes manually works as expected including the changes for PHPCS. Thank you.

**Comment by yorkshire-pudding** [comment]
> Applying the diff as a patch against version 1.x-1.0.3 failed on my local

I can see why that would happen.  In the version people have installed, there is the text:

```
; Added by Backdrop CMS packaging script on 2022-08-26
project = simplei
version = 1.x-1.0.3
timestamp = 1661575152
```

which doesn't exist in the repo, itself, only in release zip files.
Because I added a dependency to 1.28.0 or above, that causes a conflict with the version in the release.
